import Foundation

extension GameSession {
    func snapshot() -> NativeGameSnapshot {
        let result = phase == .ended ? (winner == nil ? "nagari" : "win") : nil
        return NativeGameSnapshot(
            stateVersion: 3,
            gameUuid: gameUuid,
            gameMode: mode.rawValue,
            turnNumber: turnNumber,
            pointValue: pointValue,
            computerDifficulty: difficulty,
            phase: phase.snapshotName,
            currentPlayer: currentPlayer,
            humanHand: ids(hands[.human]),
            computerHand: ids(hands[.computer]),
            computerAHand: mode == .gostop ? ids(hands[.computerA]) : nil,
            computerBHand: mode == .gostop ? ids(hands[.computerB]) : nil,
            floorCards: ids(floorCards), drawPile: ids(drawPile),
            humanCaptured: ids(captured[.human]),
            computerCaptured: ids(captured[.computer]),
            computerACaptured: mode == .gostop ? ids(captured[.computerA]) : nil,
            computerBCaptured: mode == .gostop ? ids(captured[.computerB]) : nil,
            humanGoCount: goCounts[.human] ?? 0,
            computerGoCount: goCounts[.computer] ?? 0,
            computerAGoCount: mode == .gostop ? goCounts[.computerA] ?? 0 : nil,
            computerBGoCount: mode == .gostop ? goCounts[.computerB] ?? 0 : nil,
            winner: winner, roundResult: result, settlement: settlement,
            lastAction: lastAction, createdAt: createdAt,
            shakeCounts: stringDictionary(shakeCounts),
            bombCounts: stringDictionary(bombCounts),
            bombSkips: stringDictionary(bombSkips),
            gookjinAsPee: stringDictionary(gookjinAsPee),
            shakenMonths: stringDictionary(shakenMonths.mapValues(Array.init)),
            missionCardIds: missionCards.map(\.id),
            ppeokCounts: stringDictionary(ppeokCounts),
            ppeokOwners: Dictionary(uniqueKeysWithValues: ppeokOwners.map { (String($0.key), $0.value.rawValue) }),
            roundMultiplier: roundMultiplier,
            lastDiscardedCardId: lastDiscardedCardId,
            lastDiscardedBy: lastDiscardedBy,
            emptyCaptureStreaks: stringDictionary(emptyCaptureStreaks),
            turnCounts: stringDictionary(turnCounts),
            openingPpeokCounts: stringDictionary(openingPpeokCounts),
            interimPointDeltas: stringDictionary(interimPointDeltas),
            lastGoPlayer: lastGoPlayer,
            gookjinChoiceMade: stringDictionary(gookjinChoiceMade),
            startingPlayer: startingPlayer,
            phasePlayer: phase.snapshotPlayer,
            pendingMatchState: pendingMatch.map { .init(cardId: $0.card.id, candidateIds: $0.candidates.map(\.id), player: $0.player, stage: $0.stage) },
            stagedPairState: stagedPair.map { .init(newCardId: $0.newCard.id, floorCardId: $0.floorCard.id, player: $0.player) },
            activePlayedCardId: activePlayedCard?.id,
            pendingChongtongState: pendingChongtong,
            sweepCounts: stringDictionary(sweepCounts),
            openingPpeokTotals: stringDictionary(openingPpeokTotals),
            humanSweepCount: sweepCounts[.human] ?? 0,
            humanBombCount: bombCounts[.human] ?? 0,
            humanShakeCount: shakeCounts[.human] ?? 0,
            humanPpeokCount: ppeokCounts[.human] ?? 0,
            humanOpeningPpeokCount: openingPpeokTotals[.human] ?? 0
        )
    }
}
